Repository datalayer/jupyter-ui, pull requests merged in 2024-06, with the labels that each got.

#241 chore: add jupyter cell to lexical
  examples/lexical/src/App.tsx
  examples/lexical/webpack.config.js
  packages/lexical/src/convert/NbFormatToLexical.tsx
  packages/lexical/src/examples/editor/Editor.tsx
  packages/lexical/src/examples/plugins/DraggableBlockPlugin/index.tsx
  packages/lexical/src/index.tsx
  packages/lexical/src/nodes/JupyterCellNode.tsx
  packages/lexical/src/plugins/ComponentPickerMenuPlugin.tsx
  packages/lexical/src/plugins/JupyterCellPlugin.tsx
  packages/lexical/src/plugins/JupyterPlugin.tsx
  packages/react/src/components/notebook/cell/sidebar/CellSidebar.tsx
  packages/react/src/jupyter/JupyterContext.tsx
  packages/react/src/jupyter/ipywidgets/classic/manager.ts
  packages/react/src/jupyter/ipywidgets/lab/manager.ts
Labels: enhancement

#251 example: get outputs as json
  packages/react/src/components/codemirror/CodeMirrorEditor.tsx
  packages/react/src/components/output/Output.tsx
  packages/react/src/components/output/OutputState.ts
  packages/react/src/examples/Cell.tsx
  packages/react/src/examples/Output.tsx
  packages/react/webpack.config.js
Labels: examples

#253 fix: cra example
  examples/cra/src/examples/cell/CellComponents.tsx
  examples/cra/src/examples/labapp/JupyterLabHeadlessApp.tsx
  packages/react/package.json
Labels: fix

#248 feat: adding support to markdown cells (#247)
  packages/react/src/components/cell/Cell.tsx
  packages/react/src/components/cell/CellAdapter.ts
  packages/react/src/components/cell/CellCommands.ts
Labels: feature
