Repository datalayer/jupyter-ui, pull requests merged in 2024-09, with the labels that each got.

#299 Fix jupyterlite version
  packages/react/package.json
Labels: bug

#291 Added notifyOnComplete parameter for KernelExecutor
  .vscode/settings.json
  packages/react/src/components/output/Output.tsx
  packages/react/src/components/output/OutputAdapter.ts
  packages/react/src/components/output/OutputExecutor.ts
  packages/react/src/jupyter/kernel/Kernel.ts
  packages/react/src/jupyter/kernel/KernelExecutor.ts
Labels: feature

#304 Fix notebook shortcuts
  packages/react/src/components/notebook/NotebookCommands.ts
  packages/react/src/examples/Outputs.tsx
  packages/react/src/examples/notebooks/NotebookOutputs.ipynb.json
  packages/react/webpack.config.js
Labels: fix

#316 Release: 0 18 8 and 0.18.09
  packages/react/package.json
  packages/react/src/examples/NotebookURL.tsx
  packages/react/webpack.config.js
Labels: release
