Repository datalayer/jupyter-ui, pull requests merged in 2024-08, with the labels that each got.

#283 fix: typo
  packages/react/src/components/notebook/NotebookAdapter.ts
Labels: enhancement

#284 Fix typo
  packages/react/src/components/notebook/NotebookAdapter.ts
Labels: typo

#293 Fix Undo Redo Stack
  packages/react/src/components/notebook/NotebookCommands.ts
Labels: feature
